#!/usr/bin/env bash
# Migrate a legacy tasks.md into the atomic tasks/ directory structure.
#
# Per Constitution Article IX (Directive 2: Atomic Injunction), a single
# tasks.md file is FORBIDDEN. Task artifacts MUST be a tasks/ directory
# of individual T-XXX-[name].md files.
#
# This migration is conservative: it moves the existing tasks.md into
# tasks/T-001-legacy-migrated.md and creates index.md / traceability.md
# stubs if they do not already exist. The human operator is expected to
# review the migrated file and split it into proper atomic tasks before
# proceeding with /atomicspec.implement.
#
# Usage:
#   ./migrate-legacy-tasks.sh <feature-directory>
#
# Example:
#   ./migrate-legacy-tasks.sh specs/001-my-feature

set -e

FEATURE_DIR="${1:-}"

if [[ -z "$FEATURE_DIR" ]]; then
    echo "ERROR: feature directory argument required" >&2
    echo "Usage: $0 <feature-directory>" >&2
    exit 1
fi

if [[ ! -d "$FEATURE_DIR" ]]; then
    echo "ERROR: Not a directory: $FEATURE_DIR" >&2
    exit 1
fi

LEGACY_TASKS="$FEATURE_DIR/tasks.md"
TASKS_DIR="$FEATURE_DIR/tasks"
INDEX="$FEATURE_DIR/index.md"
TRACEABILITY="$FEATURE_DIR/traceability.md"

if [[ ! -f "$LEGACY_TASKS" ]]; then
    echo "ERROR: No legacy tasks.md at $LEGACY_TASKS" >&2
    echo "Nothing to migrate." >&2
    exit 1
fi

if [[ -d "$TASKS_DIR" ]] && [[ -n "$(ls -A "$TASKS_DIR" 2>/dev/null)" ]]; then
    echo "ERROR: $TASKS_DIR already exists with content." >&2
    echo "Refusing to overwrite. Resolve the conflict manually." >&2
    exit 1
fi

echo "Migrating legacy tasks.md → atomic tasks/ directory"
echo "  Feature: $FEATURE_DIR"
echo ""

mkdir -p "$TASKS_DIR"

MIGRATED_FILE="$TASKS_DIR/T-001-legacy-migrated.md"
cat > "$MIGRATED_FILE" <<EOF
# T-001: Legacy tasks.md (migrated)

**Status**: NEEDS_REVIEW
**Source**: Migrated from $LEGACY_TASKS
**Action Required**: Split this file into atomic T-XXX-[name].md files per the Atomic Injunction.

---

EOF
cat "$LEGACY_TASKS" >> "$MIGRATED_FILE"

mv "$LEGACY_TASKS" "$FEATURE_DIR/tasks.md.migrated-backup"

if [[ ! -f "$INDEX" ]]; then
    cat > "$INDEX" <<EOF
# Feature Index (stub — generated by migrate-legacy-tasks.sh)

> **Action required**: Populate this file as the entry point for the feature.
> See .specify/knowledge/stations/ for the Atomic Traceability Model.

## Tasks

- [T-001-legacy-migrated.md](tasks/T-001-legacy-migrated.md) — NEEDS_REVIEW
EOF
    echo "  + created index.md stub"
fi

if [[ ! -f "$TRACEABILITY" ]]; then
    cat > "$TRACEABILITY" <<EOF
# Traceability Matrix (stub — generated by migrate-legacy-tasks.sh)

> **Action required**: Populate requirement-to-task mappings after splitting
> T-001-legacy-migrated.md into atomic tasks.

| Requirement | Task(s) | Status |
| ----------- | ------- | ------ |
| (pending)   | T-001   | NEEDS_REVIEW |
EOF
    echo "  + created traceability.md stub"
fi

echo ""
echo "Migration complete."
echo ""
echo "  Legacy tasks.md → $FEATURE_DIR/tasks.md.migrated-backup"
echo "  New atomic file  → $MIGRATED_FILE"
echo ""
echo "NEXT STEPS:"
echo "  1. Review $MIGRATED_FILE"
echo "  2. Split each original task heading into a separate T-XXX-[name].md"
echo "  3. Update index.md and traceability.md accordingly"
echo "  4. Delete the .migrated-backup file when satisfied"
echo "  5. Re-run /atomicspec.implement to proceed"
